CREATE DATABASE PROJETO_ADABD;

USE PROJETO_ADABD;

CREATE TABLE funcionario (
Nome_funcionario VARCHAR (40),
ID_FUNCIONARIO INT IDENTITY,
ATENDIMENTOS INT,
SALARIO INT,
COMISSAO INT
CONSTRAINT PK_ID_FUNCIONARIO PRIMARY KEY(ID_FUNCIONARIO)
)

CREATE TABLE cliente(
Nome_cliente VARCHAR(40),
CPF_CLIENTE INT,
DATA_DE_NASCIMENTO INT,
CONSTRAINT PK_CPF_CLIENTE PRIMARY KEY(CPF_CLIENTE)
)


CREATE TABLE produtos(
COD_PRODUTO INT,
VALOR_PRODUTO INT,
DESC_PRODUTO VARCHAR (40)
CONSTRAINT PK_COD_PROD PRIMARY KEY(COD_PRODUTO)
)


CREATE TABLE operacao(
COD_DA_OPERACAO INT,
ID_FUNCIONARIO INT,
CPF_CLIENTE INT,
COD_PRODUTO INT,
CONSTRAINT PK_cod_da_operacao PRIMARY KEY (COD_DA_OPERACAO),
CONSTRAINT FK_ID_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO)
	REFERENCES funcionario(ID_FUNCIONARIO),
CONSTRAINT FK_CPF_CLIENTE FOREIGN KEY (CPF_CLIENTE)
	REFERENCES cliente (CPF_CLIENTE),
CONSTRAINT fk_cod_produto FOREIGN KEY (COD_PRODUTO)
	REFERENCES produtos (COD_PRODUTO)
)
